finish

diff --git a/0x02-shell_redirections/103-the_biggest_fan b/0x02-shell_redirections/103-the_biggest_fan
--- a/0x02-shell_redirections/103-the_biggest_fan
+++ b/0x02-shell_redirections/103-the_biggest_fan
@@ -1,2 +1,10 @@
 #!/bin/bash
-tail -n +2 | cut -f 1 | sort -k 1 | uniq -c | sort rnk 1 | head -n 11 | rev | cut -d '' -f 1 | rev
+
+# Check if the log file exists
+if [ ! -f webserver.log ]; then
+	    echo "Log file 'webserver.log' not found."
+	        exit 1
+fi
+
+# Read the log file and extract hosts/IPs
+awk '{print $1}' webserver.log | sort | uniq -c | sort -rn | head -n 11
